version: '3'

networks:
  devnetwork:
    driver: bridge

services:
 zookeeper:
   image: wurstmeister/zookeeper:latest
   container_name: zookeeper
   hostname: zookeeper
   ports:
    - 2181:2181
   networks:
    - devnetwork
 kafka:
   image: wurstmeister/kafka:latest
   container_name: kafka
   hostname: kafka
   ports:
    - target: 9092
      published: 9092
      protocol: tcp
      mode: host
   environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9091,OUTSIDE://localhost:9092
    - KAFKA_LISTENERS=INSIDE://:9091,OUTSIDE://:9092
    - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
   depends_on:
    - zookeeper
   networks:
    - devnetwork